### ISSUE TITLE
Could the author please publish a video demonstrating how to run the code from scratch?

### ISSUE THREAD

**Issue by IMoonKeyBoy** [ada-shen/icCNN#5]

**Comment by ada-shen** [comment]
你好，我看到你发了知乎讨论我们论文实验的问题，因为没有互相关注，我只能发一条私信给你，所以在这里回复更多细节。

知乎和GitHub私信我容易忽视，我们可以邮件讨论更多训练细节，我的邮箱地址是wen_shen@sjtu.edu.cn；

1. 我们IJCAI论文中汇报的结果的模型文件已上传到https://b2y4v0n4v2.feishu.cn/drive/folder/fldcnwJeKnPEuQVydwhqNH8op5d，你可以下载之后运行看看。

2. 如果你在自己的系统上从头训练模型，其结果与我们的结果会存在一些差异，这个是系统不同导致的。我们自己在不同系统上跑出来的结果也有所差异，但都显著地展现出可解释性。

希望我们可以邮件进一步沟通实验细节。
